### ISSUE TITLE
Provider Error when parsing replay using the odota parser

### ISSUE THREAD

**Issue by FranzHahn** [skadistats/clarity#306] opened 2023-10-04 11:11 UTC
When trying to parse a replay with the odota parser I get a "no provider found" Exception in clarity:

`skadistats.clarity.ClarityException: oops. no provider found for required usage point interface opendota.processors.warding.OnWardKilled`

This issue had come up in a similar way before in the odota parser repo, where the bug seemed to be caused by using the wrong JRE. But after ensuring that I'm running 1.8, I am clueless as to what the cause of the error is. I've not gotten a response in the odota repo, so I was thinking, since it's an exception from within clarity, someone here might be able to help?

The setup is a fresh install of Eclipse with Maven, and freshly cloned odota repo.

**Comment by spheenik** [comment] 2023-10-07 10:37
You have to enable "annotation processors" when compiling clarity.

**Comment by FranzHahn** [comment] 2023-10-13 07:12
Simply enabling this option didn't seem to solve the problem, now I get the following Provirder error:

`skadistats.clarity.ClarityException: oops. no provider found for required usage point interface skadistats.clarity.processor.packet.UsesPacketReader`

I also missed another error that was further above, regarding SLF4J: 

`SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.`

I've unsuccessfully tried including a separate version of the `slf4j-api-2.0.5.jar` in the build path, but that didn't seem to solve the problem.

I'd really appreciate further assistance. I hope it's not just me being stupid.

**Comment by BusyLivingDota** [comment] 2023-11-20 05:26
I got similar problem:

```
Exception in thread "main" skadistats.clarity.ClarityException: oops. no provider found for required usage point interface skadistats.clarity.examples.lifestate.OnEntityDying
	at skadistats.clarity.processor.runner.ExecutionModel.requireProvider(ExecutionModel.java:122)
	at skadistats.clarity.processor.runner.ExecutionModel.requireEventListener(ExecutionModel.java:144)
	at skadistats.clarity.processor.runner.ExecutionModel.requireProcessorClass(ExecutionModel.java:78)
	at skadistats.clarity.processor.runner.ExecutionModel.addProcessor(ExecutionModel.java:48)
	at skadistats.clarity.processor.runner.AbstractRunner.addProcessorsToModel(AbstractRunner.java:40)
	at skadistats.clarity.processor.runner.AbstractRunner.addProcessorsToModel(AbstractRunner.java:38)
	at skadistats.clarity.processor.runner.AbstractRunner.createExecutionModel(AbstractRunner.java:31)
	at skadistats.clarity.processor.runner.AbstractRunner.initWithProcessors(AbstractRunner.java:46)
	at skadistats.clarity.processor.runner.AbstractFileRunner.initAndRunWith(AbstractFileRunner.java:36)
	at skadistats.clarity.processor.runner.SimpleRunner.runWith(SimpleRunner.java:33)
	at busyliving.TableauProcessor.run(TableauProcessor.java:156)
	at busyliving.dirOperation.Main.main(Main.java:43)
```
I have the box for "Enable annotation processing" checked in the Idea settings but it doesn't work out. Shall I enable "annotation processors" elsewhere? Maybe in the Build.grardle.kts file?

**Comment by spheenik** [comment] 2023-11-20 08:08
I'm assuming you use 3.0 BusyLivingDota?
Try to enable it in your `build.gradle.kts` like so:
https://github.com/skadistats/clarity/blob/master/build.gradle.kts#L28

**Comment by BusyLivingDota** [comment] 2023-11-20 09:58
I see. "annotationProcessor("org.atteo.classindex:classindex:3.13")" works out here. GPT told me to use sth like "annotationProcessor("group:name:version")". I mistakenly thought I have to refer somewhere from Clarity. Thanks for the answer!

**Comment by spheenik** [comment] 2023-11-20 11:55
@FranzHahn 

You don't need to checkout / build clarity itself. This makes it easier.
You just need to checkout clarity-examples, and use the provided documentation to run examples.
From there, you can customize an example to build your own.

**Comment by mkdzt** [comment] 2024-02-25 12:21
I have the same issue with Kotlin project.
`Exception in thread "main" skadistats.clarity.ClarityException: oops. no provider found for required usage point interface org.example.OnEntitySpawned`

**Comment by spheenik** [comment] 2024-02-25 23:24
You have to enable annotation processors. Somehow.

**Comment by mkdzt** [comment] 2024-02-27 17:27
Can u told how to do it with gradle(kts)?

**Comment by mkdzt** [comment] 2024-02-29 04:26
I read previous comments, and try it, but doesn't help me.
I use it like in doc - gradle implementation in project.

**Comment by spheenik** [comment] 2024-02-29 07:47
I can't say what the problem is. Can you show your `build.gradle.kts`?

**Comment by mkdzt** [comment] 2024-02-29 16:41
it's simpliest `plugins {
    kotlin("jvm") version "1.9.22"
}

group = "org.example"
version = "1.0-SNAPSHOT"

repositories {
    mavenCentral()
}

dependencies {
    annotationProcessor("org.atteo.classindex:classindex:3.13")
    implementation("com.skadistats:clarity:3.0.2")
    testImplementation("org.jetbrains.kotlin:kotlin-test")
}

tasks.test {
    useJUnitPlatform()
}`

**Comment by spheenik** [comment] 2024-03-06 15:46
From my perspective, this is all that's needed.
Where is `@OnEntitySpawned` defined? In your package `org.example`, meaning you copied it over from `clarity-examples`?
Maybe you do not have the class that provides this event?
In `clarity-examples`, it is here: https://github.com/skadistats/clarity-examples/blob/master/src/main/java/skadistats/clarity/examples/lifestate/SpawnsAndDeaths.java

**Comment by spheenik** [comment] 2024-03-06 15:47
Notice
```java
@Provides({ OnEntitySpawned.class, OnEntityDying.class, OnEntityDied.class })
```

If you have no class that has this, then that's your problem.

**Closed** 2024-04-27 12:43 UTC
