### ISSUE TITLE
port yasps combatlog changes

### ISSUE THREAD

**Issue by howardc93** [skadistats/clarity#37] opened 2015-04-05 13:45 UTC
Latest snapshot seems to have broken functionality on input streams:

For example:
```
java -jar parser/target/stats-0.1.0.one-jar.jar < ../testfiles/1193091757.dem 
```
This works fine.

However:
```
cat ../testfiles/1193091757.dem | java -jar parser/target/stats-0.1.0.one-jar.jar 
```
and
```
wget -qO- http://replay111.valve.net/570/1375055798_10047699.dem.bz2 | bunzip2 | java -jar parser/target/stats-0.1.0.one-jar.jar 
```
give an IOException "illegal seek".

**Comment by spheenik** [comment] 2015-04-05 14:46
Can you point me to the code of stats-0.1.0?

**Comment by howardc93** [comment] 2015-04-05 14:48
https://github.com/yasp-dota/yasp/blob/teamfight/parser/src/main/java/yasp/Main.java

I'm using input stream source with system.in

**Comment by spheenik** [comment] 2015-04-05 14:51
can u post a stacktrace or mail it to clarity@martin.schrodt.org?

**Comment by spheenik** [comment] 2015-04-05 14:55
btw: those here from YaspCombatLog:
```java
//yasp
        stunDurationIdx = descriptor.getIndexForKey("stun_duration");
        xpReasonIdx = descriptor.getIndexForKey("xp_reason");
        locationXIdx = descriptor.getIndexForKey("location_x");
        locationYIdx = descriptor.getIndexForKey("location_y");

````

Is this standard? If so, I would merge that into my code...

**Comment by spheenik** [comment] 2015-04-05 15:03
nevermind, I can reproduce it here.

**Comment by spheenik** [comment] 2015-04-05 15:21
fixed in https://github.com/skadistats/clarity/commit/494ec27ba4efab63375e2ae8005622957bf20e15

I put a new snapshot online, so updating snapshot should be enough...

**Comment by howardc93** [comment] 2015-04-05 15:36
XP reason works, the other fields seem to be present, but not populated.

**Comment by howardc93** [comment] 2015-04-05 16:01
Fixed on most of the test files, but now getting:
```
Exception in thread "main"
java.lang.reflect.InvocationTargetException

        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.simontuffs.onejar.Boot.run(Boot.java:340)
        at com.simontuffs.onejar.Boot.main(Boot.java:166)
Caused by: java.lang.RuntimeException: java.io.EOFException
        at skadistats.clarity.event.Event.raise(Event.java:25)
        at skadistats.clarity.processor.runner.AbstractRunner.runWith(AbstractRunner.java:59)
        at yasp.Main.run(Main.java:430)
        at yasp.Main.main(Main.java:438)
        ... 6 more
Caused by: java.io.EOFException
        at skadistats.clarity.source.InputStreamSource.readByte(InputStreamSource.java:38)
        at skadistats.clarity.source.Source.readVarInt32(Source.java:30)
        at skadistats.clarity.processor.reader.InputSourceProcessor.processSource(InputSourceProcessor.java:65)
        at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:599)
        at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:73)
        at skadistats.clarity.event.Event.raise(Event.java:23)
        ... 9 more
```
This is on an ARDM match, https://github.com/yasp-dota/testfiles/blob/master/1189263979_ardm.dem

This same error occurs on an invalid file (shouldn't the error be "not a valid replay file"?)
```
Exception in thread "main"
java.lang.reflect.InvocationTargetException


        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)

        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

        at java.lang.reflect.Method.invoke(Method.java:606)

        at com.simontuffs.onejar.Boot.run(Boot.java:340)

        at com.simontuffs.onejar.Boot.main(Boot.java:166)

Caused by: java.io.EOFException

        at skadistats.clarity.source.InputStreamSource.readBytes(InputStreamSource.java:49)

        at skadistats.clarity.source.Source.readBytes(Source.java:20)

        at skadistats.clarity.source.Source.ensureDemoHeader(Source.java:70)

        at skadistats.clarity.processor.runner.SimpleRunner.<init>(SimpleRunner.java:11)

        at yasp.Main.run(Main.java:430)

        at yasp.Main.main(Main.java:438)

        ... 6 more
```

**Comment by howardc93** [comment] 2015-04-05 16:03
The invalid file is just "asdf", so possibly it's trying to read more bytes than are present in the file?

**Comment by spheenik** [comment] 2015-04-05 17:59
you were correct. if there were less than 8 bytes, it would bail with EOFException. Made that one more clear.

I cannot reproduce the bug with the ARDM-match. works fine here.
My code:

https://github.com/skadistats/clarity-examples/blob/master/src/main/java/skadistats/clarity/examples/test/Main.java

**Comment by howardc93** [comment] 2015-04-05 19:19
Have you tried using System.in and cat to pipe in a stream?

**Comment by howardc93** [comment] 2015-04-05 19:23
Test passed in CI, looks like I just had a locally corrupt replay file.

**Comment by spheenik** [comment] 2015-04-05 19:24
right, I just tried, piping also works :)

**Comment by spheenik** [comment] 2015-04-05 19:24
are you around in #dota2replay by chance?

**Comment by howardc93** [comment] 2015-04-05 19:25
I have been a few times in the past but not recently

**Comment by spheenik** [comment] 2015-04-05 19:27
I see. I have been absent there for a long time, but I try to be around now,
So if there is a problem requiring more interaction, come by!

**Comment by howardc93** [comment] 2015-04-11 17:31
re: getIndexForKey:

I think the full descriptor list is here, so you could add all of them to CombatLog:
https://github.com/skadistats/clarity-protobuf/blob/6638354a436a0d5c995a5684190dc9b61f2edd54/src/main/proto/dota_usermessages.proto#L863

I'm guessing you just regenerate the .proto file periodically based on SteamKit, but the CombatLog methods in clarity need to be updated as well when the protobuf definitions change.  

It would be nice if the methods/Idx values could be updated automatically when the protobufs change.  I don't think you could update the helper methods automatically in this way, but perhaps it's best for the end-user application to implement these methods, as users may want to translate/compile the combat log names differently?

**Comment by spheenik** [comment] 2015-04-11 22:00
on an unrelated note:

https://github.com/skadistats/clarity/commit/a2dd3784701340dd1c78cea02369e84b8db488b3

if you use @OnTickStart or @OnTickEnd, you have to add a boolean parameter to your event listener

**Comment by howardc93** [comment] 2015-04-11 22:20
Does this need to be updated as well?

https://github.com/skadistats/clarity/blob/master/src/main/java/skadistats/clarity/processor/gameevents/CombatLog.java#L54

How much are you planning to add to the default clarity CombatLog class?  Just the additional Idx values, or the helper methods as well?

**Comment by spheenik** [comment] 2015-04-11 22:34
For sure, fixed, thanks!

I would add the additional Idx values, and remove the helpers and put them on the example.
So you would need to implement the helpers the way you need them, and would be able to use the Idx stuff? Deal?

**Comment by howardc93** [comment] 2015-04-11 22:47
What will you do with:

```
        private final StringTable combatLogNames;
        private final GameEvent event;
```

Will you expose them to the client, or retain methods for readCombatLogName and a getter for each of the combat log values?

The following differ from your reference implementation:
```
 public boolean isTargetHero() {
            if (targetHeroIdx==null) {
                return true;
            }
            return event.getProperty(targetHeroIdx);
        }
        public boolean isAttackerHero() {
            if (attackerHeroIdx==null){
                return true;
            }
            return event.getProperty(attackerHeroIdx);
        }
        
        private String translate(String in) {
            if (in!=null){
                if (in.startsWith("item_")){
                    in=in.substring("item_".length());
                }
            }
            return in;
        }
        public int getGoldReason() {
            if (goldReasonIdx==null){
                return 0;
            }
            return event.getProperty(goldReasonIdx);
        }
        public int getXpReason() {
            if (xpReasonIdx==null){
                return 0;
            }
            return event.getProperty(xpReasonIdx);
        }
        public int getStunDuration() {
            return event.getProperty(stunDurationIdx);
        }
        public int getLocationX() {
            return event.getProperty(locationXIdx);
        }
        public int getLocationY() {
            return event.getProperty(locationYIdx);
        }
        public String getValueName(){
            return translate(readCombatLogName(getValue()));
        }
        public String getTargetNameCompiled() {
            return (isTargetIllusion() ? "illusion_" : "") + getTargetName();
        }
        public String getAttackerNameCompiled() {
            return (isAttackerIllusion() ? "illusion_" : "") + getAttackerName();
        }
```

I added a null check in the first two to account for replays that don't have that field set (very old replays)
Similar for the getGoldReason and XpReason methods.
I implemented translate so that it just strips the item_ from the combat log name for items.  This makes it the same as the name used in http://www.dota2.com/jsfeed/itemdata
Added getters for xpreason, stun, locationx, locationy 
Added getValueName to be able to read combat log name for value (needed to determine combat log name when purchasing an item)
And finally the I prepend illusion_ to the target name to mark it an illusion, but this is probably client-specific.

**Comment by howardc93** [comment] 2015-04-11 22:59
Also, Alice updated protobufs yesterday, I don't know if clarity-protobuf is fully up-to-date:

https://github.com/AliceStats/Alice/commit/129dd7d59b163b328a0857adcb68efde055adfb9

**Comment by spheenik** [comment] 2015-04-11 23:03
right, I would add a null check for everything that has an idx of type Integer, since it can be null for old replays.

I wouldnt take the translate-function, if the client wants to remove "item_", it should do it himself. 
I also would remove the getXXXCompiled() functions, and leave those up to the client.

I *could* expose the game event. I mean, why not. Do you need it?

I would not expose the StringTable, because CombatLogEntry exposes everything it needs from that table. Basically, @OnCombatLogEntry is just some convenience function on ctx.getProcessor(StringTables.class) and @OnGameEvent anyway.

**Comment by howardc93** [comment] 2015-04-11 23:12
I don't need it, and I just noticed you have a getGameEvent() method anyway.  
So I guess just make a getter for each Idx element, and leave translate/compile up to the client.

You should add getValueName as the client will be unable to get the value's combat log name otherwise (unless you want to make readCombatLog public)

You should also remove translate() from all the functions that are currently using it (since translation is going to be left up to the client)

After this I should be able to get rid of YASPCombatLog and just use the default clarity implementation.

**Comment by spheenik** [comment] 2015-04-11 23:23
ok, will implement soon-ish :)

**Comment by howardc93** [comment] 2015-05-01 08:24
I also added the following method for debugging:
```
        public String toString(){
            return event.toString();
        }
```

6.84 added four new combat log types, 14-17.

**Comment by howardc93** [comment] 2015-06-10 17:53
I did this in my own fork.

**Comment by spheenik** [comment] 2015-06-10 17:55
is there some commit I could merge?

**Comment by howardc93** [comment] 2015-06-10 18:04
Here's the merged version:

https://github.com/yasp-dota/clarity/blob/master/src/main/java/skadistats/clarity/processor/gameevents/CombatLog.java

Unfortunately I applied the changes on top of a lot of other things, so I
can't just submit a pull request.

I am also in the process of testing it to make sure I did it right.

**Closed** 2015-06-14 19:45 UTC
