### ISSUE TITLE
Class Baseline Missing Error When Parsing Games

### ISSUE THREAD

**Issue by Aelvangunduz** [skadistats/clarity#153] opened 2018-01-22 17:15 UTC
Hello,

I was trying to parse matches 3691811839 and 3691287542 using opendota's parser and I'm getting the error below. I have not modified anything in the parser code.

```
skadistats.clarity.ClarityException: Baseline for class CDOTA_Unit_Hero_Silencer (618) not found.
	at skadistats.clarity.processor.entities.Entities.getBaseline(Entities.java:189)
	at skadistats.clarity.processor.entities.Entities.onPacketEntities(Entities.java:126)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:25)
	at skadistats.clarity.processor.reader.InputSourceProcessor.processEmbedded(InputSourceProcessor.java:254)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:25)
	at skadistats.clarity.processor.reader.InputSourceProcessor.processSource(InputSourceProcessor.java:181)
	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
	at skadistats.clarity.event.Event.raise(Event.java:25)
	at skadistats.clarity.processor.runner.AbstractFileRunner.initAndRunWith(AbstractFileRunner.java:38)
	at skadistats.clarity.processor.runner.SimpleRunner.runWith(SimpleRunner.java:36)
	at opendota.Parse.<init>(Parse.java:172)
	at opendota.Main$MyHandler.handle(Main.java:27)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by spheenik** [comment] 2018-01-23 09:15
Hmm, these seem to amass. Same issue as #152, I suppose.
@STRATZ-Ken: Do you see elevated error rates?

**Comment by Aelvangunduz** [comment] 2018-01-23 09:21
Yeah definitely, parsing has been very hit and miss. Sometimes it simply fails and sometimes it fails halfway through though I don't know whether this is due to ODota or clarity.

**Comment by spheenik** [comment] 2018-01-23 09:23
This is in clarity, not ODota.

Valve seem to have changed something subtle in the replay format. I will have a look.

**Comment by STRATZ-Ken** [comment] 2018-03-02 22:56
Sorry for the delay @spheenik.  Nope.  I have not had any errors.  I dont use Baseline for anything.  I wait until an Entity is created, store it in an array then cross reference the StringTable name with the names from the client files.

**Comment by spheenik** [comment] 2018-03-05 13:22
Closing as a duplicate of #152.

**Closed by spheenik** 2018-03-05 13:22 UTC
